# Site settings
title: Union Cataloging Projects
brand: Union Cataloging Projects
description: > # this means to ignore newlines until "baseurl:"
  Author, Title (Place: Publisher, Year)
baseurl: "/wpaunioncatalog/" # the subpath of your site, e.g. /blog/
url: "https://www.domain.com"

# Build settings
markdown: kramdown

# The navigation.
navigation:
  left:
    links:
      - title: Home
        href: /path/to/work/
      - title: Chapters
        dropdown: sections
      - title: Downloads
        dropdown: downloads
  right:
    content: searchbox.html

gems:
  - jekyll-sitemap
  - octopress-debugger
  - jekyll-lunr-js-search
