# Site settings
title: Your awesome title
brand: MY BLOG
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.google.com"
copyright: © My Company 2013

# Build settings
markdown: kramdown

# The video that plays.
video: "u7deClndzQw"

# The navigation.
navigation:
  left:
    links:
      - title: About
        href: /about/
      - title: Link 2
        href: #
      - title: Dropdown
        dropdown: sections
