# Site settings
title: Union Cataloging Projects
brand: Union Cataloging Projects
description: > # this means to ignore newlines until "baseurl:"
  Union Cataloging Projects (W.P.A. Technical Series, Library No. 1; Washington D.C., 1940)
baseurl: "/wpaunioncatalog" # the subpath of your site, e.g. /blog/
url: "https://www.domain.com"

# Build settings
markdown: kramdown
# downloads.yml is generated during the rendering, so we need to 
# ignore it or it will cause an infinite loop of re-rendering
exclude: ['_data/downloads.yml','downloads']

# The navigation.
navigation:
  left:
    links:
      - title: Home
        href: /wpaunioncatalog/
      - title: Chapters
        dropdown: sections
      - title: Downloads
        dropdown: downloads
  right:
    content: searchbox.html

gems:
  - jekyll-sitemap
  - octopress-debugger
  - jekyll-lunr-js-search
