# Site settings
title: Title of Book
brand: Title of Book
description: > # this means to ignore newlines until "baseurl:"
  Author, Title (Place: Publisher, Year)
baseurl: "/path/to/work/" # the subpath of your site, e.g. /blog/
url: "https://www.domain.com"

# Build settings
markdown: kramdown
# downloads.yml is generated during the rendering, so we need to 
# ignore it or it will cause an infinite loop of re-rendering
exclude: ['_data/downloads.yml']

# The navigation.
navigation:
  left:
    links:
      - title: Home
        href: /path/to/work/
      - title: Chapters
        dropdown: sections
      - title: Downloads
        dropdown: downloads
  right:
    content: searchbox.html

gems:
  - jekyll-sitemap
  - octopress-debugger
  - jekyll-lunr-js-search
