# Site settings
title: Title of Book
brand: Title of Book
description: > # this means to ignore newlines until "baseurl:"
  Author, Title (Place: Publisher, Year)
baseurl: "/path/to/work/" # the subpath of your site, e.g. /blog/
url: "https://www.domain.com"

# Build settings
markdown: kramdown

# The navigation.
navigation:
  left:
    links:
      - title: Home
        href: /path/to/work/
      - title: Chapters
        dropdown: sections
      - title: Downloads
        dropdown: downloads

gems:
  - jekyll-sitemap
  - octopress-debugger
